version: "3.7"

services:
  db:
    platform: linux/x86_64
    image: postgres:13 # MySQLをPostgreSQLに変更
    environment:
      POSTGRES_USER: postgres # PostgreSQL用の環境変数
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sample
    ports:
      - 5432:5432 # PostgreSQLのデフォルトポート
    volumes:
      - postgres-db:/var/lib/postgresql/data # ボリュームも変更

  front:
    build:
      context: ./gikyoku-app
      dockerfile: Dockerfile
    volumes:
      - ./gikyoku-app:/usr/src/app
    command: sh -c 'apk update && apk add --no-cache openssl && npm install && yarn dev'
    ports:
      - "8000:3000"
      - 5555:5555
    depends_on:
      - db # データベースが起動してからフロントエンドを起動

volumes:
  postgres-db: # ボリューム名を変更
    driver: local
