version: "3.7"

services:
  db:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
      MYSQL_PASSWORD: password
    ports:
      - 4306:3306
    volumes:
      - mysql-db:/var/lib/mysql
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front/app:/usr/src/app
      - front_node_modules:/usr/src/app/node_modules
    command: sh -c 'npm install && yarn dev'
    ports:
      - "8000:3000"
      - 5555:5555
volumes:
  front_node_modules:
  mysql-db:
    driver: local
