-- AlterTable
ALTER TABLE "ChildComment" ADD COLUMN     "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "ParentComment" ADD COLUMN     "ate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
