/**
 * 小劇場劇団シードスクリプト
 * 全国の小劇場劇団（プロ・アマチュア・ユース）をDBに投入
 * 大学演劇サークルは除外（seed-theater-groups.tsで別途管理）
 *
 * 使い方:
 *   set -a && source .env.local && set +a && npx tsx scripts/seed-shogekijo.ts
 */

import { PrismaClient, Region, TheaterGroupType } from '@prisma/client';

const prisma = new PrismaClient();

type ShogekijoData = {
  name: string;
  slug: string;
  groupType: TheaterGroupType;
  description?: string;
  memberCount?: number;
  foundedYear?: number;
  prefecture: string;
  region: Region;
  website?: string;
  twitter?: string;
  instagram?: string;
  corich?: string;
  otherLinks?: string[];
};

const shogekijoGroups: ShogekijoData[] = [
  // ============================================================
  // 北海道 (HOKKAIDO) - 14団体
  // ============================================================
  {
    name: 'ELEVEN NINES',
    slug: 'eleven-nines',
    groupType: 'PROFESSIONAL',
    description: '富良野塾卒塾生を中心に結成された演劇集団。納谷真大が代表を務め、演劇でしか表現できないライブエンターテイメントを追求。',
    foundedYear: 2004,
    prefecture: '北海道',
    region: 'HOKKAIDO',
    website: 'http://eleven9.jp/',
    twitter: 'elevennine_119',
    corich: 'https://stage.corich.jp/troupe/7657',
  },
  {
    name: '札幌座',
    slug: 'sapporo-za',
    groupType: 'PROFESSIONAL',
    description: '北海道演劇財団附属の創造集団。1996年にTPSとして設立、2012年に札幌座に改称。Theater ZOOを拠点に活動。',
    foundedYear: 1996,
    prefecture: '北海道',
    region: 'HOKKAIDO',
    website: 'http://www.sapporoza.com/',
    corich: 'https://stage.corich.jp/troupe/1771',
  },
  {
    name: 'yhs',
    slug: 'yhs',
    groupType: 'PROFESSIONAL',
    description: '南参を中心に札幌で結成された劇団。独自の作風で札幌演劇シーズンの常連として活躍。',
    foundedYear: 1997,
    prefecture: '北海道',
    region: 'HOKKAIDO',
    website: 'https://www.yhsweb.jp/',
  },
  {
    name: '弦巻楽団',
    slug: 'tsurumaki-gakudan',
    groupType: 'PROFESSIONAL',
    description: '弦巻啓太が北海道札幌市で旗揚げした劇団。繊細な人間ドラマを得意とし、全国的にも高い評価を受ける。',
    foundedYear: 2003,
    prefecture: '北海道',
    region: 'HOKKAIDO',
    website: 'https://tsurumaki-gakudan.com/',
  },
  {
    name: 'intro',
    slug: 'intro-sapporo',
    groupType: 'PROFESSIONAL',
    description: '伊藤わかなを中心に2006年に始動し2009年に劇団化。「ポストロック演劇団」とも呼ばれる。',
    foundedYear: 2009,
    prefecture: '北海道',
    region: 'HOKKAIDO',
    website: 'http://intro-sapporo.com/',
    corich: 'https://stage.corich.jp/troupe/3388',
  },
  {
    name: '劇団千年王國',
    slug: 'sennen-oukoku',
    groupType: 'PROFESSIONAL',
    description: '橋口幸絵を中心に設立。札幌を拠点に東京・大阪・九州や海外でも公演活動を展開。',
    foundedYear: 1999,
    prefecture: '北海道',
    region: 'HOKKAIDO',
    corich: 'https://stage.corich.jp/troupe/79',
  },
  {
    name: 'クラアク芸術堂',
    slug: 'clark-art-company',
    groupType: 'PROFESSIONAL',
    description: '小佐部明広が率いる舞台芸術団体。2011年に「劇団アトリエ」として設立し2017年に現名称に改称。',
    foundedYear: 2011,
    prefecture: '北海道',
    region: 'HOKKAIDO',
    website: 'https://www.clark-artcompany.com/',
    corich: 'https://stage.corich.jp/troupe/6912',
  },
  {
    name: '劇団イナダ組',
    slug: 'inada-gumi',
    groupType: 'PROFESSIONAL',
    description: '函館市出身の演出家・稲田博を中心に設立。札幌市豊平区を拠点に札幌演劇シーズンにも参加。',
    foundedYear: 1992,
    prefecture: '北海道',
    region: 'HOKKAIDO',
    website: 'https://www.inada-gumi.com/',
    twitter: 'inadagumiSTAFF',
  },
  {
    name: 'トランク機械シアター',
    slug: 'trunk-kikai-theater',
    groupType: 'PROFESSIONAL',
    description: '札幌を拠点とする人形劇団。保育園・幼稚園・学校などでも公演を展開。',
    foundedYear: 2012,
    prefecture: '北海道',
    region: 'HOKKAIDO',
    website: 'https://www.trunktheater.net/',
  },
  {
    name: 'Theater・ラグ・203',
    slug: 'theater-ragu-203',
    groupType: 'AMATEUR',
    description: '村松幹男が率いる札幌の劇団。ラグラグシアターを拠点にオリジナル作品を上演。',
    foundedYear: 2001,
    prefecture: '北海道',
    region: 'HOKKAIDO',
    website: 'http://www.ragu203.com/',
    corich: 'https://stage.corich.jp/troupe/2420',
  },
  {
    name: '劇団新劇場',
    slug: 'shin-gekijo',
    groupType: 'AMATEUR',
    description: '北海道で長く活動する老舗劇団。',
    foundedYear: 1961,
    prefecture: '北海道',
    region: 'HOKKAIDO',
  },
  {
    name: '劇団さっぽろ',
    slug: 'gekidan-sapporo',
    groupType: 'PROFESSIONAL',
    description: '北海道教育委員会主催の巡回小劇場に参加し、道内の幼稚園・小中高校で公演活動を行うプロ劇団。',
    prefecture: '北海道',
    region: 'HOKKAIDO',
    website: 'https://nyjtg623.wixsite.com/gekidansapporo',
  },
  {
    name: '劇団ココロワ',
    slug: 'cocorowa',
    groupType: 'AMATEUR',
    description: '札幌を拠点に活動する劇団。定期的に公演を行っている。',
    prefecture: '北海道',
    region: 'HOKKAIDO',
  },
  {
    name: '劇団5454',
    slug: 'gekidan-5454',
    groupType: 'PROFESSIONAL',
    description: '「ランドリー」と読む劇団。日常の風景をリフレッシュさせるコンセプトで札幌演劇シーズンにも参加。',
    prefecture: '北海道',
    region: 'HOKKAIDO',
    website: 'https://5454.tokyo/',
    twitter: '5454laundry',
    corich: 'https://stage.corich.jp/troupe/7855',
  },

  // ============================================================
  // 東北 (TOHOKU) - 16団体
  // ============================================================
  {
    name: '弘前劇場',
    slug: 'hirosaki-gekijo',
    groupType: 'PROFESSIONAL',
    description: '長谷川孝治を中心に1978年に旗揚げ。青森の風土に根ざした静謐な演劇で全国的に高い評価。',
    foundedYear: 1978,
    prefecture: '青森県',
    region: 'TOHOKU',
  },
  {
    name: 'ひろさき演人',
    slug: 'hirosaki-engine',
    groupType: 'AMATEUR',
    description: '鎌田龍が2018年に設立。弘前市を中心に津軽地域で活動する劇団。',
    foundedYear: 2018,
    prefecture: '青森県',
    region: 'TOHOKU',
    website: 'https://hirosakiengine.com/',
  },
  {
    name: '劇団赤い風',
    slug: 'gekidan-akai-kaze',
    groupType: 'AMATEUR',
    description: '盛岡で40年以上の歴史を持つ老舗劇団。岩手の演劇シーンを牽引。',
    foundedYear: 1983,
    prefecture: '岩手県',
    region: 'TOHOKU',
  },
  {
    name: '架空の劇団',
    slug: 'kakoo-no-gekidan',
    groupType: 'AMATEUR',
    description: '盛岡を拠点に活動する劇団。地域密着型の演劇活動を展開。',
    foundedYear: 2001,
    prefecture: '岩手県',
    region: 'TOHOKU',
    website: 'https://kakoo2001.wixsite.com/kakoo2001',
  },
  {
    name: '劇団ゆう',
    slug: 'gekidan-yuu',
    groupType: 'PROFESSIONAL',
    description: '盛岡市を拠点に活動するNPO法人の劇団。地域の演劇文化の振興に貢献。',
    prefecture: '岩手県',
    region: 'TOHOKU',
    website: 'https://www.gekidan-yuu.com/',
  },
  {
    name: '劇団コトナコナタ',
    slug: 'kotonakonata',
    groupType: 'AMATEUR',
    description: '盛岡で活動する劇団。盛岡劇場での公演に参加。',
    prefecture: '岩手県',
    region: 'TOHOKU',
    website: 'http://kotonakonata.pya.jp/',
  },
  {
    name: '仙台シアターラボ',
    slug: 'sendai-theater-labo',
    groupType: 'PROFESSIONAL',
    description: '演出家・野々下孝を中心に設立。せんだい演劇工房10-BOXを拠点に活動。2014年宮城県芸術選奨新人賞受賞。',
    foundedYear: 2010,
    prefecture: '宮城県',
    region: 'TOHOKU',
    website: 'https://sendai-theatrelabo.com/',
    twitter: 's_theatrelabo',
  },
  {
    name: "Gin's Bar",
    slug: 'gins-bar',
    groupType: 'AMATEUR',
    description: '井伸銀太郎プロデュースによる仙台の演劇ユニット。Quarter Studioを拠点に会話劇を上演。',
    prefecture: '宮城県',
    region: 'TOHOKU',
    website: 'http://ginsbar.com/',
  },
  {
    name: '東北えびす',
    slug: 'tohoku-ebisu',
    groupType: 'PROFESSIONAL',
    description: '一般社団法人として活動する仙台の演劇組織。「THEATERえびす」を運営。',
    prefecture: '宮城県',
    region: 'TOHOKU',
    website: 'https://www.tohokuebisu.com/',
  },
  {
    name: 'いわぬま市民劇団ウィープ',
    slug: 'iwanuma-weep',
    groupType: 'AMATEUR',
    description: '岩沼市民会館を拠点に活動する市民劇団。地域の文化活動に貢献。',
    prefecture: '宮城県',
    region: 'TOHOKU',
  },
  {
    name: 'わらび座',
    slug: 'warabi-za',
    groupType: 'PROFESSIONAL',
    description: '1951年創立の民族芸能をベースにした劇団。秋田県仙北市のあきた芸術村を拠点に年間約600回の公演を全国で展開。',
    foundedYear: 1951,
    prefecture: '秋田県',
    region: 'TOHOKU',
    website: 'https://www.warabi.jp/',
    twitter: 'art_warabiza',
  },
  {
    name: '劇団はちのす',
    slug: 'gekidan-hachinosu',
    groupType: 'AMATEUR',
    description: '秋田市で演劇活動をしている劇団。',
    prefecture: '秋田県',
    region: 'TOHOKU',
    website: 'http://mt-hachinosu.jpn.org/',
  },
  {
    name: '劇団山形',
    slug: 'gekidan-yamagata',
    groupType: 'AMATEUR',
    description: '創立60年を超える山形県を代表する地域劇団。',
    foundedYear: 1965,
    prefecture: '山形県',
    region: 'TOHOKU',
    website: 'https://gekiyama.wixsite.com/gekidan-yamagata',
  },
  {
    name: '劇団いわき小劇場',
    slug: 'iwaki-shogekijo',
    groupType: 'AMATEUR',
    description: 'いわき芸術文化交流館アリオス内を拠点に活動。長い歴史を持つ地域の演劇拠点。',
    foundedYear: 1969,
    prefecture: '福島県',
    region: 'TOHOKU',
    website: 'https://ilt1969.jimdofree.com/',
  },
  {
    name: '劇団ユニット・ラビッツ',
    slug: 'unit-rabbits',
    groupType: 'AMATEUR',
    description: '福島県郡山市を拠点に活動。年2回の定期公演を実施。',
    foundedYear: 2005,
    prefecture: '福島県',
    region: 'TOHOKU',
    website: 'https://www.unitrabbits.com/',
  },
  {
    name: '劇団120○EN',
    slug: 'gekidan-120en',
    groupType: 'AMATEUR',
    description: '福島市を拠点に活動。民話や歴史を下敷きとしたオリジナル作品を上演。',
    prefecture: '福島県',
    region: 'TOHOKU',
    instagram: '120en',
  },

  // ============================================================
  // 関東 (KANTO) - 東京都 100団体
  // ============================================================
  {
    name: '青年団',
    slug: 'seinendan',
    groupType: 'PROFESSIONAL',
    description: '平田オリザ主宰。「現代口語演劇」の理論と実践で知られ、日本の現代演劇を牽引する劇団。',
    foundedYear: 1983,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://www.seinendan.org/',
    twitter: 'seinendan',
  },
  {
    name: 'ナイロン100℃',
    slug: 'nylon100',
    groupType: 'PROFESSIONAL',
    description: 'ケラリーノ・サンドロヴィッチ主宰。独特のユーモアと知性溢れるコメディで人気の劇団。',
    foundedYear: 1993,
    prefecture: '東京都',
    region: 'KANTO',
    twitter: 'nylon100c',
  },
  {
    name: '大人計画',
    slug: 'otona-keikaku',
    groupType: 'PROFESSIONAL',
    description: '松尾スズキ主宰。宮藤官九郎、阿部サダヲら個性派俳優を多数輩出。',
    foundedYear: 1988,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://otonakeikaku.jp/',
  },
  {
    name: 'NODA・MAP',
    slug: 'noda-map',
    groupType: 'PROFESSIONAL',
    description: '野田秀樹主宰。言葉遊びと身体表現を融合させた独自のスタイルで日本演劇界を牽引。',
    foundedYear: 1993,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://www.nodamap.com/',
  },
  {
    name: 'チェルフィッチュ',
    slug: 'chelfitsch',
    groupType: 'PROFESSIONAL',
    description: '岡田利規主宰。独自の身体表現と「超リアル日本語」で世界的に評価される。',
    foundedYear: 1997,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://chelfitsch.net/',
  },
  {
    name: '阿佐ヶ谷スパイダース',
    slug: 'asagaya-spiders',
    groupType: 'PROFESSIONAL',
    description: '長塚圭史主宰。骨太な人間ドラマとダイナミックな演出で知られる。',
    foundedYear: 1996,
    prefecture: '東京都',
    region: 'KANTO',
  },
  {
    name: 'キャラメルボックス',
    slug: 'caramelbox',
    groupType: 'PROFESSIONAL',
    description: '成井豊主宰。エンタメ性の高い作品で幅広いファン層を獲得。動員力は小劇場界トップクラス。',
    foundedYear: 1985,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://www.caramelbox.com/',
    twitter: 'caramelbox_com',
  },
  {
    name: '新宿梁山泊',
    slug: 'shinjuku-ryozanpaku',
    groupType: 'PROFESSIONAL',
    description: '金守珍主宰。テント公演を中心にアングラ演劇の伝統を受け継ぐ。',
    foundedYear: 1987,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://www.ryozanpaku.com/',
  },
  {
    name: '劇団唐組',
    slug: 'karagumi',
    groupType: 'PROFESSIONAL',
    description: '唐十郎主宰。紅テント公演で知られるアングラ演劇の代表格。',
    foundedYear: 1988,
    prefecture: '東京都',
    region: 'KANTO',
  },
  {
    name: '東京乾電池',
    slug: 'tokyo-kandenchi',
    groupType: 'PROFESSIONAL',
    description: '柄本明主宰。飄々としたユーモアと日常のリアリティで独自の世界を築く。',
    foundedYear: 1976,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://www.tokyo-kandenchi.com/',
  },
  {
    name: '燐光群',
    slug: 'rinkogun',
    groupType: 'PROFESSIONAL',
    description: '坂手洋二主宰。社会問題を鋭く切り取る骨太な作品で知られる。',
    foundedYear: 1983,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://www.alles.or.jp/~rinkogun/',
  },
  {
    name: '流山児★事務所',
    slug: 'ryuzanji-jimusho',
    groupType: 'PROFESSIONAL',
    description: '流山児祥主宰。アングラからミュージカルまで幅広いジャンルを手がけるベテラン劇団。',
    foundedYear: 1984,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://www.ryuzanji.com/',
    twitter: 'ryuzanjicompany',
  },
  {
    name: 'モダンスイマーズ',
    slug: 'modern-swimmers',
    groupType: 'PROFESSIONAL',
    description: '蓬莱竜太主宰。日常に潜む暗部を丁寧に描く作風で高い評価。',
    foundedYear: 1999,
    prefecture: '東京都',
    region: 'KANTO',
    twitter: 'modernswimmers',
  },
  {
    name: 'KAKUTA',
    slug: 'kakuta',
    groupType: 'PROFESSIONAL',
    description: '桑原裕子主宰。小説家としても活躍し、骨太で緻密な人間ドラマを創作。',
    foundedYear: 1996,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://www.kakuta.tv/',
  },
  {
    name: '五反田団',
    slug: 'gotanda-dan',
    groupType: 'PROFESSIONAL',
    description: '前田司郎主宰。脱力系の独自のユーモアと哲学的テーマで岸田國士戯曲賞受賞。',
    foundedYear: 1997,
    prefecture: '東京都',
    region: 'KANTO',
  },
  {
    name: '庭劇団ペニノ',
    slug: 'niwa-gekidan-penino',
    groupType: 'PROFESSIONAL',
    description: 'タニノクロウ主宰。精神科医の経歴を持ち、異世界的な舞台美術と幻想的な作品で国際的に活躍。',
    foundedYear: 2000,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://niwagekidan.org/',
  },
  {
    name: '劇団桟敷童子',
    slug: 'sajiki-douji',
    groupType: 'PROFESSIONAL',
    description: '東憲司主宰。九州の土着的な世界観と圧倒的な舞台美術で独自の地位を確立。',
    foundedYear: 1999,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://sajikidouji.jimdofree.com/',
  },
  {
    name: 'アマヤドリ',
    slug: 'amayadori',
    groupType: 'PROFESSIONAL',
    description: '広田淳一主宰。身体表現と言葉の融合、群舞の美しさが特徴。',
    foundedYear: 2001,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://amayadori.co.jp/',
    twitter: 'amayadori_info',
  },
  {
    name: '劇団チョコレートケーキ',
    slug: 'chocolate-cake',
    groupType: 'PROFESSIONAL',
    description: '古川健が劇作、日澤雄介が演出。歴史的事実を基にした骨太な社会派ドラマが持ち味。',
    foundedYear: 2000,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://www.chocolatecake.jp/',
    twitter: 'choco_cake2000',
  },
  {
    name: 'DULL-COLORED POP',
    slug: 'dull-colored-pop',
    groupType: 'PROFESSIONAL',
    description: '谷賢一主宰。社会派テーマとエンタメ性を両立させた作品で知られる。',
    foundedYear: 2005,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://www.dcpop.org/',
    twitter: 'dullcoloredpop',
  },
  {
    name: 'ハイバイ',
    slug: 'hi-bye',
    groupType: 'PROFESSIONAL',
    description: '岩井秀人主宰。家族の機能不全や引きこもりなど実体験に基づく作品で注目。',
    foundedYear: 2003,
    prefecture: '東京都',
    region: 'KANTO',
  },
  {
    name: 'イキウメ',
    slug: 'ikiume',
    groupType: 'PROFESSIONAL',
    description: '前川知大主宰。SF的設定と日常を融合させた独自の世界観で岸田國士戯曲賞受賞。',
    foundedYear: 2003,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://www.ikiume.jp/',
    twitter: 'ikiume',
  },
  {
    name: '劇団た組',
    slug: 'takumi-theater',
    groupType: 'PROFESSIONAL',
    description: '加藤拓也主宰。映画・テレビでも活躍する気鋭の劇作家・演出家が率いる劇団。',
    foundedYear: 2012,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://takumitheater.jp/',
  },
  {
    name: '快快',
    slug: 'faifai',
    groupType: 'PROFESSIONAL',
    description: '集団創作による独自のデバイジング手法で、既存の演劇の枠を超えたパフォーマンスを展開。',
    foundedYear: 2004,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://faifai.tv/',
  },
  {
    name: 'ゆうめい',
    slug: 'yuumei',
    groupType: 'PROFESSIONAL',
    description: '池田亮主宰。実在の家族の記録を基にした私的ドキュメンタリー演劇で注目。岸田國士戯曲賞最終候補。',
    foundedYear: 2013,
    prefecture: '東京都',
    region: 'KANTO',
    twitter: 'yuumei_info',
  },
  {
    name: '劇団かもめんたる',
    slug: 'kamomentar',
    groupType: 'PROFESSIONAL',
    description: 'お笑いコンビ・かもめんたるの岩崎う大が作・演出を手がける演劇プロジェクト。',
    foundedYear: 2015,
    prefecture: '東京都',
    region: 'KANTO',
    twitter: 'kamomentar',
  },
  {
    name: 'ヌトミック',
    slug: 'nuthmique',
    groupType: 'PROFESSIONAL',
    description: '額田大志主宰。音楽的バックグラウンドを用いた脚本と演出で、パフォーミングアーツの枠組みを拡張。',
    foundedYear: 2016,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://nuthmique.com/',
    twitter: 'M_Nukata',
  },
  {
    name: 'コンプソンズ',
    slug: 'compsons',
    groupType: 'PROFESSIONAL',
    description: '金子鈴幸主宰。時事ネタを斬新に組み合わせる作風で岸田國士戯曲賞にノミネート。',
    foundedYear: 2016,
    prefecture: '東京都',
    region: 'KANTO',
  },
  {
    name: '贅沢貧乏',
    slug: 'zeitaku-binbou',
    groupType: 'PROFESSIONAL',
    description: '山田由梨主宰。実在の場所や個人の記憶をモチーフにしたサイトスペシフィックな作品。',
    foundedYear: 2012,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://zeitakubinbou.com/',
    twitter: 'zeitakubinbou',
  },
  {
    name: 'ままごと',
    slug: 'mamagoto',
    groupType: 'PROFESSIONAL',
    description: '柴幸男主宰。時間や空間の概念を独自に再構築する詩的な作品で岸田國士戯曲賞受賞。',
    foundedYear: 2009,
    prefecture: '東京都',
    region: 'KANTO',
  },
  {
    name: '鳥公園',
    slug: 'tori-koen',
    groupType: 'PROFESSIONAL',
    description: '西尾佳織主宰。言葉と身体の関係を丁寧に探求する作品で注目される。',
    foundedYear: 2007,
    prefecture: '東京都',
    region: 'KANTO',
  },
  {
    name: '城山羊の会',
    slug: 'shiroyagi-no-kai',
    groupType: 'PROFESSIONAL',
    description: '山内ケンジ主宰。不条理な日常を「演出をしない」独自のスタイルで描く。',
    foundedYear: 2004,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://shiroyaginokai.com/',
  },
  {
    name: 'うさぎストライプ',
    slug: 'usagi-stripe',
    groupType: 'PROFESSIONAL',
    description: '大池容子主宰。「どうせ死ぬのに」をテーマに死と日常を地続きに描く。',
    foundedYear: 2010,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://usagistripe.com/',
    twitter: 'usagi_stripe',
  },
  {
    name: 'タカハ劇団',
    slug: 'takaha-gekidan',
    groupType: 'PROFESSIONAL',
    description: '高羽彩主宰。社会問題を取材に基づいて描くプロデュースユニット。',
    foundedYear: 2005,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://takaha-gekidan.net/',
    twitter: 'takaha_gekidan',
  },
  {
    name: '劇団はえぎわ',
    slug: 'haegiwa',
    groupType: 'PROFESSIONAL',
    description: 'ノゾエ征爾主宰。ユーモアと叙情が同居する独自の世界観。',
    foundedYear: 1999,
    prefecture: '東京都',
    region: 'KANTO',
  },
  {
    name: 'ほろびて',
    slug: 'horobite',
    groupType: 'PROFESSIONAL',
    description: '細川洋平主宰。言葉と身体の関係を実験的に探求。',
    foundedYear: 2009,
    prefecture: '東京都',
    region: 'KANTO',
    twitter: '_horobite',
  },
  {
    name: '劇団フルタ丸',
    slug: 'furutamaru',
    groupType: 'PROFESSIONAL',
    description: 'フルタジュン主宰。ナイトコメディを得意とし、下北沢を拠点に活動。',
    foundedYear: 2002,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://furutamaru.com/',
    corich: 'https://stage.corich.jp/troupe/1009',
  },
  {
    name: 'ナカゴー',
    slug: 'nakagoo',
    groupType: 'PROFESSIONAL',
    description: '鎌田順也により結成。王子小劇場を拠点に独自の笑いの世界を展開。',
    foundedYear: 2006,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://nakagoo.com/',
  },
  {
    name: 'JACROW',
    slug: 'jacrow',
    groupType: 'PROFESSIONAL',
    description: '「大人の小劇場エンターテインメント」をコンセプトに社会的テーマを会話劇で描く。',
    foundedYear: 2001,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://www.jacrow.com/',
  },
  {
    name: '劇団スーパー・エキセントリック・シアター',
    slug: 'super-eccentric-theater',
    groupType: 'PROFESSIONAL',
    description: '三宅裕司座長。ミュージカル・アクション・コメディを特徴とするエンタメ劇団。',
    foundedYear: 1979,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://www.set1979.com/',
    twitter: 'SET_1979',
  },
  {
    name: '劇団ノーミーツ',
    slug: 'no-meets',
    groupType: 'PROFESSIONAL',
    description: '「NO密で濃密なひとときを」をテーマにフルリモートで活動する新世代劇団。',
    foundedYear: 2020,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://nomeets2020.studio.site/',
    twitter: 'gekidan_nomeets',
  },
  {
    name: '東京にこにこちゃん',
    slug: 'tokyo-niconico-chan',
    groupType: 'PROFESSIONAL',
    description: '萩田頌豊與主宰。勢いのあるコメディ劇団。',
    foundedYear: 2013,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://tokyoniconicochan.amebaownd.com/',
  },
  {
    name: 'ONEOR8',
    slug: 'oneor8',
    groupType: 'PROFESSIONAL',
    description: '田村孝裕主宰。日常のリアルを丁寧に描く会話劇が持ち味。',
    foundedYear: 1997,
    prefecture: '東京都',
    region: 'KANTO',
  },
  {
    name: 'ゴツプロ!',
    slug: 'gotsupro',
    groupType: 'PROFESSIONAL',
    description: '塚原大助プロデュース。40代男性俳優を中心に骨太な人間ドラマを展開。',
    foundedYear: 2015,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://52pro.info/',
  },
  {
    name: 'Mrs.fictions',
    slug: 'mrs-fictions',
    groupType: 'PROFESSIONAL',
    description: '舞台芸術の創造と発展を目的に活動する舞台製作者集団。',
    foundedYear: 2007,
    prefecture: '東京都',
    region: 'KANTO',
    twitter: 'Mrs_fictions',
  },
  {
    name: '劇団め組',
    slug: 'gekidan-megumi',
    groupType: 'PROFESSIONAL',
    description: '吉祥寺を拠点に活動する小劇場演劇の老舗。',
    foundedYear: 1984,
    prefecture: '東京都',
    region: 'KANTO',
  },
  {
    name: '電動夏子安置システム',
    slug: 'dendo-natsuko-anchi-system',
    groupType: 'PROFESSIONAL',
    description: '竹田哲士主宰。「ロジカル・コメディ」を掲げるシチュエーション・コメディ劇団。',
    foundedYear: 2000,
    prefecture: '東京都',
    region: 'KANTO',
    corich: 'https://stage.corich.jp/troupe/698',
  },
  {
    name: 'あひるなんちゃら',
    slug: 'ahiru-nanchara',
    groupType: 'PROFESSIONAL',
    description: '脱力系の笑いとゆるい空気感が特徴。2003年ユニットとして始動し2005年に劇団化。',
    foundedYear: 2003,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'http://www.ahirunanchara.com/',
    corich: 'https://stage.corich.jp/troupe/278',
  },
  {
    name: '劇団温泉ドラゴン',
    slug: 'onsen-dragon',
    groupType: 'PROFESSIONAL',
    description: '在日コリアンの歴史や社会的マイノリティのテーマを力強く描く。',
    foundedYear: 2015,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://www.onsendragon.com/',
  },
  {
    name: '劇団AUN',
    slug: 'gekidan-aun',
    groupType: 'PROFESSIONAL',
    description: '池袋を拠点。シェイクスピア作品の翻案など古典と現代の融合を試みる。',
    foundedYear: 2000,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'http://aun.la.coocan.jp/',
    twitter: 'aun_company',
  },
  {
    name: '劇団スポーツ',
    slug: 'gekidan-sport',
    groupType: 'PROFESSIONAL',
    description: 'ポップでエネルギッシュな作品を展開する若手劇団。',
    foundedYear: 2016,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://gekidansport.com/',
    twitter: 'gekidansport',
  },
  {
    name: '劇団肋骨蜜柑同好会',
    slug: 'rokkotsu-mikan',
    groupType: 'PROFESSIONAL',
    description: '筑波大学出身メンバーを中心に旗揚げ。幻想的な世界を描く。',
    foundedYear: 2010,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://rokkotsumikan.com/',
    twitter: 'rokkotsu_mikan',
  },
  {
    name: 'ピチチ5',
    slug: 'pichichi5',
    groupType: 'PROFESSIONAL',
    description: '福原充則主宰。ナンセンスコメディと社会風刺を織り交ぜた独自の笑いの世界。',
    foundedYear: 2002,
    prefecture: '東京都',
    region: 'KANTO',
    twitter: 'm_fuckhara',
  },
  {
    name: '毛皮族',
    slug: 'kegawazoku',
    groupType: 'PROFESSIONAL',
    description: '江本純子主宰。過激でエネルギッシュなパフォーマンスと独自の女性的世界観。',
    foundedYear: 2000,
    prefecture: '東京都',
    region: 'KANTO',
  },
  {
    name: '岡崎藝術座',
    slug: 'okazaki-art-theatre',
    groupType: 'PROFESSIONAL',
    description: '神里雄大主宰。移民や多文化をテーマにドキュメンタリー的手法で演劇を創作。',
    foundedYear: 2003,
    prefecture: '東京都',
    region: 'KANTO',
  },
  {
    name: '劇団献身',
    slug: 'gekidan-kenshin',
    groupType: 'PROFESSIONAL',
    description: '奥村徹也主宰。笑いとペーソスが同居する独自のコメディ。',
    foundedYear: 2013,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://gekidankenshin.wordpress.com/',
  },
  {
    name: '劇団papercraft',
    slug: 'gekidan-papercraft',
    groupType: 'PROFESSIONAL',
    description: '海路主宰。紙を組み立てるように脚本を舞台にする繊細な作品。',
    foundedYear: 2020,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://gekidan-papercraft.amebaownd.com/',
  },
  {
    name: '文学座',
    slug: 'bungakuza',
    groupType: 'PROFESSIONAL',
    description: '1937年創立の日本を代表する新劇団。岸田國士らが設立。',
    foundedYear: 1937,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://www.bungakuza.com/',
  },
  {
    name: '劇団俳優座',
    slug: 'haiyuza',
    groupType: 'PROFESSIONAL',
    description: '1944年設立。六本木に専用劇場を持ち社会派演劇を中心に上演。',
    foundedYear: 1944,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://haiyuza.net/',
  },
  {
    name: '劇団青年座',
    slug: 'seinenza',
    groupType: 'PROFESSIONAL',
    description: '創作劇の上演を柱に据え、新作オリジナルドラマを上演し続ける老舗新劇団。',
    foundedYear: 1954,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://www.seinenza.com/',
  },
  {
    name: '演劇集団 円',
    slug: 'engeki-shudan-en',
    groupType: 'PROFESSIONAL',
    description: '橋爪功が長年代表。実力派俳優を多数擁する名門劇団。',
    foundedYear: 1975,
    prefecture: '東京都',
    region: 'KANTO',
    twitter: 'engekisyudan_en',
    instagram: 'engekisyudan_en',
  },
  {
    name: '劇団NLT',
    slug: 'nlt',
    groupType: 'PROFESSIONAL',
    description: '喜劇専門の劇団。翻訳喜劇を中心に上演。',
    foundedYear: 1964,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'http://www.nlt.co.jp/',
    twitter: 'nlt_seisaku',
  },
  {
    name: 'テアトル・エコー',
    slug: 'teatoru-echo',
    groupType: 'PROFESSIONAL',
    description: '1954年設立。コメディを得意とし声優も多数在籍する老舗劇団。',
    foundedYear: 1954,
    prefecture: '東京都',
    region: 'KANTO',
  },
  {
    name: '劇団昴',
    slug: 'theater-company-subaru',
    groupType: 'PROFESSIONAL',
    description: '翻訳劇と古典を得意とする新劇団。声優としても活躍する団員多数。',
    foundedYear: 1976,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://www.theatercompany-subaru.com/',
  },
  {
    name: '劇団俳小',
    slug: 'haishou',
    groupType: 'PROFESSIONAL',
    description: '個性的で魅力的な役者が多数所属する劇団。',
    foundedYear: 1949,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://www.haishou.co.jp/',
  },
  {
    name: '劇団朋友',
    slug: 'gekidan-foryou',
    groupType: 'PROFESSIONAL',
    description: '1954年の「劇団新人会」を前身とし1994年に改称。長い歴史を持つ実力派劇団。',
    foundedYear: 1954,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://www.gekidanforyou.com/',
  },
  {
    name: 'KUNIO',
    slug: 'kunio',
    groupType: 'PROFESSIONAL',
    description: '杉原邦生主宰。古典から現代まで幅広い作品を手掛けるプロデュース公演カンパニー。',
    foundedYear: 2004,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://kunio.me/',
  },
  {
    name: '劇団扉座',
    slug: 'tobiraza',
    groupType: 'PROFESSIONAL',
    description: '横内謙介主宰。1982年「善人会議」として旗揚げ、1993年に改称。',
    foundedYear: 1982,
    prefecture: '東京都',
    region: 'KANTO',
    website: 'https://tobiraza.co.jp/',
    twitter: 'tobiraza',
  },
  {
    name: '劇団番町ボーイズ☆',
    slug: 'bancho-boys',
    groupType: 'AMATEUR',
    description: 'ソニー・ミュージックが主宰する若手男性演劇集団。',
    foundedYear: 2015,
    prefecture: '東京都',
    region: 'KANTO',
    twitter: 'bancho_boys_5',
    instagram: 'bancho_boys_5',
  },
  {
    name: '中野成樹＋フランケンズ',
    slug: 'nakano-shigeki-frankens',
    groupType: 'AMATEUR',
    description: '既存戯曲を「誤意訳」する独自の手法で知られる演劇ユニット。',
    foundedYear: 2002,
    prefecture: '東京都',
    region: 'KANTO',
  },
  {
    name: '劇団東京座',
    slug: 'gekidan-tokyoza',
    groupType: 'AMATEUR',
    description: '2019年設立。東京を拠点に活動する劇団。',
    foundedYear: 2019,
    prefecture: '東京都',
    region: 'KANTO',
    twitter: 'GekidanTokyoza',
  },
  {
    name: 'ぬいぐるみハンター',
    slug: 'nuigurumi-hunter',
    groupType: 'YOUTH',
    description: '佐藤佐吉演劇祭にも出演する若手劇団。エネルギッシュなパフォーマンスが特徴。',
    prefecture: '東京都',
    region: 'KANTO',
  },
  {
    name: '東葛スポーツ',
    slug: 'tokatsu-sports',
    groupType: 'YOUTH',
    description: '金山寿甲主宰。「パチンコ（上）」で岸田國士戯曲賞受賞。ドキュメンタリー的手法で注目。',
    foundedYear: 2015,
    prefecture: '東京都',
    region: 'KANTO',
  },

  // ============================================================
  // 中部 (CHUBU) - 37団体
  // ============================================================
  {
    name: '劇団カタコンベ',
    slug: 'gekidan-catacombe',
    groupType: 'AMATEUR',
    description: '新潟市を拠点に活動する劇団。未経験者も受け入れている。',
    prefecture: '新潟県',
    region: 'CHUBU',
    website: 'https://geki-ctcmb.jimdofree.com/',
  },
  {
    name: '劇団羅針盤',
    slug: 'gekidan-rashinban',
    groupType: 'AMATEUR',
    description: '金沢市を拠点とする劇団。地域の演劇イベントに積極的に参加。',
    prefecture: '石川県',
    region: 'CHUBU',
    website: 'https://gekirashinban.com/',
  },
  {
    name: 'POTLUCK THEATER',
    slug: 'potluck-theater',
    groupType: 'PROFESSIONAL',
    description: '東京で活動していた演出家・島貴之が石川県で演劇を行うために作った集団。',
    prefecture: '石川県',
    region: 'CHUBU',
    website: 'https://potlucktheater.com/',
  },
  {
    name: 'Theater Angelus',
    slug: 'theater-angelus',
    groupType: 'PROFESSIONAL',
    description: '金沢から世界へ地域演劇を発信する劇団。',
    prefecture: '石川県',
    region: 'CHUBU',
    website: 'https://theaterangelus.com/',
  },
  {
    name: '劇団はぐるま',
    slug: 'gekidan-haguruma-gifu',
    groupType: 'AMATEUR',
    description: '1954年に岐阜市で創設。ミュージカル・小劇場公演を年2回発表。1983年サントリー地域文化賞受賞。',
    foundedYear: 1954,
    prefecture: '岐阜県',
    region: 'CHUBU',
    website: 'https://www.gekidanhaguruma.com/',
    instagram: 'gekidan_haguruma1954',
  },
  {
    name: '劇団ジャブジャブサーキット',
    slug: 'jab-jab-circuit',
    groupType: 'PROFESSIONAL',
    description: '1985年に岐阜大学OBを中心に旗揚げ。東京・大阪でも定期公演を行う三大都市巡業スタイル。',
    foundedYear: 1985,
    prefecture: '岐阜県',
    region: 'CHUBU',
    website: 'https://jjcofficehp.wixsite.com/toppage',
  },
  {
    name: 'SPAC-静岡県舞台芸術センター',
    slug: 'spac',
    groupType: 'PROFESSIONAL',
    description: '1995年設立の日本初の公立文化事業集団。宮城聰芸術総監督のもと多彩な作品を上演。',
    foundedYear: 1995,
    prefecture: '静岡県',
    region: 'CHUBU',
    website: 'https://spac.or.jp/',
    twitter: '_SPAC_',
    instagram: 'spac_shizuoka',
  },
  {
    name: '劇団静芸',
    slug: 'gekidan-shizugei',
    groupType: 'AMATEUR',
    description: '1948年に創立された静岡市の老舗地域劇団。',
    foundedYear: 1948,
    prefecture: '静岡県',
    region: 'CHUBU',
    website: 'https://shizugei.jp/',
  },
  {
    name: '劇団たんぽぽ',
    slug: 'gekidan-tanpopo',
    groupType: 'PROFESSIONAL',
    description: '1946年設立。浜松市を拠点に全国の子どもたちに向けて公演を行う児童劇専門プロ劇団。',
    foundedYear: 1946,
    prefecture: '静岡県',
    region: 'CHUBU',
    website: 'https://www.gekidan-tanpopo.com/',
    twitter: 'gekidan_tanpopo',
  },
  {
    name: '劇団からっかぜ',
    slug: 'gekidan-karakkaze',
    groupType: 'AMATEUR',
    description: '1954年設立の浜松市の劇団。70年以上の歴史。',
    foundedYear: 1954,
    prefecture: '静岡県',
    region: 'CHUBU',
    website: 'https://karakkaze.org/',
    twitter: 'karakkaze1954',
  },
  {
    name: 'MUNA-POCKET COFFEEHOUSE',
    slug: 'muna-pocket',
    groupType: 'PROFESSIONAL',
    description: '浜松市で活動するクリエイティブチーム。2019年ふじのくに芸術祭大賞受賞。',
    prefecture: '静岡県',
    region: 'CHUBU',
    website: 'https://679.jp/',
  },
  {
    name: 'オイスターズ',
    slug: 'oysters',
    groupType: 'PROFESSIONAL',
    description: '2005年に平塚直隆が結成した名古屋拠点の劇団。若手演出家コンクール最優秀賞等受賞多数。',
    foundedYear: 2005,
    prefecture: '愛知県',
    region: 'CHUBU',
    website: 'https://oysters.official.jp/',
  },
  {
    name: '少年王者舘',
    slug: 'shonen-oujakan',
    groupType: 'PROFESSIONAL',
    description: '1982年に天野天街が名古屋で旗揚げ。映像と身体を駆使した幻想的世界観で知られる伝説的劇団。',
    foundedYear: 1982,
    prefecture: '愛知県',
    region: 'CHUBU',
    website: 'http://www.oujakan.jp/',
  },
  {
    name: '劇団B級遊撃隊',
    slug: 'b-kyu-yugekitai',
    groupType: 'PROFESSIONAL',
    description: '1986年設立。シニカルでナンセンス、不条理な作風で名古屋小劇場を代表する劇団。',
    foundedYear: 1986,
    prefecture: '愛知県',
    region: 'CHUBU',
    website: 'https://bkyuyugekitai.wixsite.com/bkyuyugekitai',
    corich: 'https://stage.corich.jp/troupe/977',
  },
  {
    name: '刈馬演劇設計社',
    slug: 'karuma-engeki',
    groupType: 'PROFESSIONAL',
    description: '2012年始動。劇作家協会新人戯曲賞、せんだい短編戯曲賞大賞など受賞多数。',
    foundedYear: 2012,
    prefecture: '愛知県',
    region: 'CHUBU',
    website: 'https://karumaengeki.wixsite.com/karuma',
    corich: 'https://stage.corich.jp/troupe/8141',
  },
  {
    name: '劇団あおきりみかん',
    slug: 'aokiri-mikan',
    groupType: 'PROFESSIONAL',
    description: '1998年に南山大学演劇部メンバーを中心に旗揚げ。名古屋を代表する劇団。',
    foundedYear: 1998,
    prefecture: '愛知県',
    region: 'CHUBU',
    website: 'https://aokirimikan.net/',
    twitter: 'aokirimikan',
    instagram: 'aokirimikan1998',
    corich: 'https://stage.corich.jp/troupe/1571',
  },
  {
    name: '劇団うりんこ',
    slug: 'gekidan-urinko',
    groupType: 'PROFESSIONAL',
    description: '1973年設立の東海地方初の児童劇専門プロ劇団。うりんこ劇場を構える。',
    foundedYear: 1973,
    prefecture: '愛知県',
    region: 'CHUBU',
    website: 'https://www.urinko.jp/',
    twitter: 'urinkojp',
  },
  {
    name: '劇団名古屋',
    slug: 'gekidan-nagoya',
    groupType: 'AMATEUR',
    description: '1957年設立。働きながら芝居を続けるリアリズム演劇の社会人劇団。',
    foundedYear: 1957,
    prefecture: '愛知県',
    region: 'CHUBU',
    website: 'https://www.gekidan758.com/',
    twitter: 'gekidan758',
  },
  {
    name: '劇団そらのゆめ',
    slug: 'sora-no-yume',
    groupType: 'PROFESSIONAL',
    description: '2011年に劇団うりんこ出身者が創立。演劇で豊かに生きる力を育むことを目指す。',
    foundedYear: 2011,
    prefecture: '愛知県',
    region: 'CHUBU',
    website: 'http://soranoyume.com/',
    instagram: 'soranoyume_official',
  },
  {
    name: '総合劇集団俳優館',
    slug: 'haiyukan',
    groupType: 'PROFESSIONAL',
    description: '名古屋の総合劇集団。幅広いジャンルの舞台作品を上演。',
    prefecture: '愛知県',
    region: 'CHUBU',
    website: 'http://www.hi-you-can.com/',
  },
  {
    name: '劇団風の子中部',
    slug: 'kazenoko-chubu',
    groupType: 'PROFESSIONAL',
    description: '全国で活動する児童演劇専門劇団「劇団風の子」の中部支部。',
    foundedYear: 1950,
    prefecture: '愛知県',
    region: 'CHUBU',
    website: 'https://www.kazenokotyubu.com/',
  },
  {
    name: '円盤ライダー',
    slug: 'enban-rider',
    groupType: 'PROFESSIONAL',
    description: '渡部将之が2006年に旗揚げした演劇パフォーマンスユニット。',
    foundedYear: 2006,
    prefecture: '愛知県',
    region: 'CHUBU',
    website: 'https://enbanrider.com/',
    twitter: 'enbanrider_masa',
  },
  {
    name: '人形劇団むすび座',
    slug: 'musubi-za',
    groupType: 'PROFESSIONAL',
    description: '名古屋を拠点に全国で公演を行うプロの人形劇団。',
    prefecture: '愛知県',
    region: 'CHUBU',
    website: 'http://www.musubiza.co.jp/',
  },
  {
    name: 'KUDAN Project',
    slug: 'kudan-project',
    groupType: 'PROFESSIONAL',
    description: '名古屋で活動するプロジェクト型の演劇団体。',
    prefecture: '愛知県',
    region: 'CHUBU',
    website: 'http://www.officek.jp/kudan/',
  },
  {
    name: '劇団クセックACT',
    slug: 'ksec-act',
    groupType: 'AMATEUR',
    description: '名古屋で活動する劇団。定期的に公演を実施。',
    prefecture: '愛知県',
    region: 'CHUBU',
    website: 'https://www.ksec-act.com/',
  },
  {
    name: '虚構オメガ',
    slug: 'kyoko-omega',
    groupType: 'AMATEUR',
    description: '名古屋を拠点に活動する劇団。',
    prefecture: '愛知県',
    region: 'CHUBU',
    website: 'https://omegafiction.com/',
  },

  // ============================================================
  // 関西 (KANSAI) - 75団体
  // ============================================================
  {
    name: '劇団☆新感線',
    slug: 'gekidan-shinkansen',
    groupType: 'PROFESSIONAL',
    description: '1980年に大阪芸術大学出身者で旗揚げ。いのうえひでのり主宰。大阪発祥の代表的劇団。',
    foundedYear: 1980,
    prefecture: '大阪府',
    region: 'KANSAI',
    website: 'https://www.vi-shinkansen.co.jp/',
  },
  {
    name: '南河内万歳一座',
    slug: 'minamikawachi-banzai-ichiza',
    groupType: 'PROFESSIONAL',
    description: '内藤裕敬が作・演出。1980年に大阪芸術大学有志により結成。',
    foundedYear: 1980,
    prefecture: '大阪府',
    region: 'KANSAI',
    website: 'https://banzai-ichiza.com/',
  },
  {
    name: '劇団太陽族',
    slug: 'gekidan-taiyozoku',
    groupType: 'PROFESSIONAL',
    description: '1982年旗揚げ。社会の出来事をモチーフに現代を生きる人間のかかわりを丁寧に描く。',
    foundedYear: 1982,
    prefecture: '大阪府',
    region: 'KANSAI',
    twitter: 'taiyo_zoku',
  },
  {
    name: '劇団そとばこまち',
    slug: 'gekidan-sotoba-komachi',
    groupType: 'PROFESSIONAL',
    description: '1976年に京都大学学内サークルとして発足。現在は大阪・十三を拠点にエンターテインメント時代劇を上演。',
    foundedYear: 1976,
    prefecture: '大阪府',
    region: 'KANSAI',
    website: 'https://sotobakomachi.com/',
    twitter: 'sotoba_komachi',
  },
  {
    name: '匿名劇壇',
    slug: 'tokumei-gekidan',
    groupType: 'PROFESSIONAL',
    description: '2011年結成。福谷圭祐主宰。第23回OMS戯曲賞大賞受賞。',
    foundedYear: 2011,
    prefecture: '大阪府',
    region: 'KANSAI',
    website: 'https://tokumeigekidan.jimdofree.com/',
    twitter: 'fuku_tokumei',
    corich: 'https://stage.corich.jp/troupe/7332',
  },
  {
    name: 'THE ROB CARLTON',
    slug: 'the-rob-carlton',
    groupType: 'PROFESSIONAL',
    description: '2010年結成。上質なコメディを追求する関西の注目劇団。',
    foundedYear: 2010,
    prefecture: '大阪府',
    region: 'KANSAI',
    website: 'http://www.rob-carlton.jp/',
    twitter: 'TheRobCarlton',
  },
  {
    name: '劇団壱劇屋',
    slug: 'gekidan-ichigekiya',
    groupType: 'PROFESSIONAL',
    description: '2005年結成。パントマイム・ダンス・アクションなど多様なジャンルを融合したエンタメ劇団。',
    foundedYear: 2005,
    prefecture: '大阪府',
    region: 'KANSAI',
    twitter: 'ichigekiya',
  },
  {
    name: 'iaku',
    slug: 'iaku',
    groupType: 'PROFESSIONAL',
    description: '劇作家・演出家の横山拓也による大阪発の演劇ユニット。',
    prefecture: '大阪府',
    region: 'KANSAI',
    website: 'https://www.iaku.jp/',
  },
  {
    name: '劇団Patch',
    slug: 'gekidan-patch',
    groupType: 'PROFESSIONAL',
    description: '2012年結成。関西出身の男性だけの演劇集団。',
    foundedYear: 2012,
    prefecture: '大阪府',
    region: 'KANSAI',
    website: 'https://www.west-patch.com/',
    twitter: 'west_patch',
  },
  {
    name: '突劇金魚',
    slug: 'totsugeki-kingyo',
    groupType: 'PROFESSIONAL',
    description: 'サリngROCKを中心に結成。第15回OMS戯曲賞大賞受賞。',
    prefecture: '大阪府',
    region: 'KANSAI',
    twitter: 't_kinnngyo',
    corich: 'https://stage.corich.jp/troupe/2984',
  },
  {
    name: '劇団レトルト内閣',
    slug: 'gekidan-retoruto-naikaku',
    groupType: 'PROFESSIONAL',
    description: '2001年創立。「エレガンスロック」を掲げる大阪の劇団。',
    foundedYear: 2001,
    prefecture: '大阪府',
    region: 'KANSAI',
    website: 'https://www.retoruto.com/',
    twitter: 'retonai',
  },
  {
    name: 'ステージタイガー',
    slug: 'stage-tiger',
    groupType: 'PROFESSIONAL',
    description: '2009年結成。「笑えて泣けるストレートプレイ」を基本に活動。',
    foundedYear: 2009,
    prefecture: '大阪府',
    region: 'KANSAI',
    corich: 'https://stage.corich.jp/troupe/4075',
  },
  {
    name: '劇団大阪',
    slug: 'gekidan-osaka',
    groupType: 'AMATEUR',
    description: '1971年創立。社会問題を扱う作品を中心に活動。劇団員35名。',
    foundedYear: 1971,
    memberCount: 35,
    prefecture: '大阪府',
    region: 'KANSAI',
    website: 'https://g-osaka.jimdofree.com/',
    twitter: 'g_osaka103',
    corich: 'https://stage.corich.jp/troupe/3704',
  },
  {
    name: '無名劇団',
    slug: 'mumei-gekidan',
    groupType: 'PROFESSIONAL',
    description: '2002年設立。大阪・西成区にアトリエを持ち地域活性化にも取り組む。',
    foundedYear: 2002,
    prefecture: '大阪府',
    region: 'KANSAI',
    website: 'https://mumeigekidan.net/',
  },
  {
    name: '空晴',
    slug: 'karappare',
    groupType: 'PROFESSIONAL',
    description: '2007年結成。ランニングシアターダッシュの元メンバー5人により設立。',
    foundedYear: 2007,
    prefecture: '大阪府',
    region: 'KANSAI',
    website: 'http://www.karappare.com/',
  },
  {
    name: '玉造小劇店',
    slug: 'tamazukuri-shogekiten',
    groupType: 'PROFESSIONAL',
    description: '大阪市中央区玉造に拠点を置く「お芝居を提供するお店」。',
    prefecture: '大阪府',
    region: 'KANSAI',
    website: 'https://tama-show.jpn.org/',
  },
  {
    name: 'ヨーロッパ企画',
    slug: 'europe-kikaku',
    groupType: 'PROFESSIONAL',
    description: '1998年結成。上田誠主宰。京都を拠点にコメディにこだわった演劇やSF群像劇を創作。映画「サマータイムマシン・ブルース」原作。',
    foundedYear: 1998,
    prefecture: '京都府',
    region: 'KANSAI',
    website: 'https://www.europe-kikaku.com/',
  },
  {
    name: 'MONO',
    slug: 'mono-kyoto',
    groupType: 'PROFESSIONAL',
    description: '1989年に京都の演劇人により結成。会話劇を中心に関西小劇場を代表する劇団。',
    foundedYear: 1989,
    prefecture: '京都府',
    region: 'KANSAI',
  },
  {
    name: '地点',
    slug: 'chiten',
    groupType: 'PROFESSIONAL',
    description: '三浦基が率いる劇団。テクストの独自の語り方で知られる前衛的な舞台表現を追究。',
    foundedYear: 2005,
    prefecture: '京都府',
    region: 'KANSAI',
    website: 'https://chiten.org/',
  },
  {
    name: '烏丸ストロークロック',
    slug: 'karasuma-stroke-rock',
    groupType: 'PROFESSIONAL',
    description: '1999年に柳沼昭徳を中心に設立。京都を拠点に現代演劇を創作。',
    foundedYear: 1999,
    prefecture: '京都府',
    region: 'KANSAI',
    website: 'https://www.karasuma69.org/',
    twitter: 'karasuma69',
  },
  {
    name: '劇団衛星',
    slug: 'gekidan-eisei',
    groupType: 'PROFESSIONAL',
    description: '1995年設立。京都を拠点に小劇場での演劇表現を極める。',
    foundedYear: 1995,
    prefecture: '京都府',
    region: 'KANSAI',
    website: 'http://eisei.info/',
  },
  {
    name: '木ノ下歌舞伎',
    slug: 'kinoshita-kabuki',
    groupType: 'PROFESSIONAL',
    description: '2006年より京都を中心に活動。歴史的文脈を踏まえつつ現代における歌舞伎演目上演の可能性を発信。',
    foundedYear: 2006,
    prefecture: '京都府',
    region: 'KANSAI',
    website: 'https://kinoshita-kabuki.org/',
    twitter: 'kinoshitakabuki',
    corich: 'https://stage.corich.jp/troupe/719',
  },
  {
    name: '悪い芝居',
    slug: 'warui-shibai',
    groupType: 'PROFESSIONAL',
    description: '山崎彬主宰。ポップカルチャーとアングラを融合させた独自の世界観。',
    foundedYear: 2004,
    prefecture: '京都府',
    region: 'KANSAI',
    website: 'https://waruishibai.jp/',
  },
  {
    name: '努力クラブ',
    slug: 'doryoku-club',
    groupType: 'PROFESSIONAL',
    description: '2011年に合田団地と佐々木峻一を中心に結成。京都の劇団。',
    foundedYear: 2011,
    prefecture: '京都府',
    region: 'KANSAI',
    twitter: 'goudareo',
  },
  {
    name: '笑の内閣',
    slug: 'shou-no-naikaku',
    groupType: 'PROFESSIONAL',
    description: '2005年に京都で旗揚げ。リングで本当にプロレスをする芝居と時事ネタ芝居を得意とする。',
    foundedYear: 2005,
    prefecture: '京都府',
    region: 'KANSAI',
  },
  {
    name: 'VOGA',
    slug: 'voga',
    groupType: 'PROFESSIONAL',
    description: '1997年に結成。京都・大阪を中心に神社・教会・美術館等でも活動。',
    foundedYear: 1997,
    prefecture: '京都府',
    region: 'KANSAI',
    website: 'https://lowotarvoga.net/',
    twitter: 'VOGA_OFFICIAL',
    corich: 'https://stage.corich.jp/troupe/1371',
  },
  {
    name: '幻灯劇場',
    slug: 'gentou-gekijou',
    groupType: 'PROFESSIONAL',
    description: '2013年設立。京都を拠点に活動。関西演劇祭2022にも参加。',
    foundedYear: 2013,
    prefecture: '京都府',
    region: 'KANSAI',
  },
  {
    name: '安住の地',
    slug: 'anju-no-chi',
    groupType: 'PROFESSIONAL',
    description: '2017年設立。演劇を軸に音楽・写真・映像・ファッションと協働する京都の集団。',
    foundedYear: 2017,
    prefecture: '京都府',
    region: 'KANSAI',
    twitter: 'anju_nochi',
  },
  {
    name: '兵庫県立ピッコロ劇団',
    slug: 'piccolo-gekidan',
    groupType: 'PROFESSIONAL',
    description: '1994年設立。日本初の県立公立劇団。尼崎のピッコロシアターを拠点に全国公演も展開。',
    foundedYear: 1994,
    prefecture: '兵庫県',
    region: 'KANSAI',
    website: 'https://piccolo-theater.jp/troupe/',
    twitter: 'piccolo_theater',
  },
  {
    name: '劇団赤鬼',
    slug: 'gekidan-akaoni',
    groupType: 'PROFESSIONAL',
    description: '1995年に神戸大学演劇サークルOBにより旗揚げ。エネルギッシュなエンタメが特徴。',
    foundedYear: 1995,
    prefecture: '兵庫県',
    region: 'KANSAI',
  },
  {
    name: '劇団道化座',
    slug: 'gekidan-dougeza',
    groupType: 'PROFESSIONAL',
    description: '創立75年を超える神戸拠点の劇団。児童劇から一般演劇まで幅広く全国で公演。',
    foundedYear: 1950,
    prefecture: '兵庫県',
    region: 'KANSAI',
    website: 'https://www.dougeza.com/',
    twitter: 'gekidan_dougeza',
  },
  {
    name: '劇団四紀会',
    slug: 'gekidan-shikikai',
    groupType: 'AMATEUR',
    description: '1957年創立。神戸市元町を拠点に68年以上活動を続ける。',
    foundedYear: 1957,
    prefecture: '兵庫県',
    region: 'KANSAI',
    website: 'https://www.shikikai.com/',
  },
  {
    name: '演劇集団和歌山',
    slug: 'engeki-shudan-wakayama',
    groupType: 'AMATEUR',
    description: '1970年結成。和歌浦小劇場を拠点に和歌山の歴史を題材にした創作劇を上演。',
    foundedYear: 1970,
    memberCount: 11,
    prefecture: '和歌山県',
    region: 'KANSAI',
    twitter: 'enshuwakayama',
    instagram: 'ensyuwakayama',
  },

  // ============================================================
  // 中国・四国 (CHUGOKU_SHIKOKU) - 18団体
  // ============================================================
  {
    name: '鳥の劇場',
    slug: 'bird-theatre-tottori',
    groupType: 'PROFESSIONAL',
    description: '鳥取市鹿野町の廃校を劇場に改装しまちおこしを推進するNPO法人。芸術監督・中島諒人が主宰。',
    foundedYear: 2006,
    prefecture: '鳥取県',
    region: 'CHUGOKU_SHIKOKU',
    website: 'https://www.birdtheatre.org/',
    twitter: 'bird_theatre',
    instagram: 'bird_theatre',
  },
  {
    name: '劇団Yプロジェクト',
    slug: 'gekidan-y-project',
    groupType: 'AMATEUR',
    description: '松江市を拠点に演劇を通して地域づくりに貢献。',
    foundedYear: 1999,
    prefecture: '島根県',
    region: 'CHUGOKU_SHIKOKU',
    instagram: 'ypro_shimane',
  },
  {
    name: '岡山劇団SKAT!!',
    slug: 'okayama-skat',
    groupType: 'AMATEUR',
    description: '殺陣やダンスを取り入れたエンターテインメント性の高い地域密着型劇団。',
    foundedYear: 2015,
    prefecture: '岡山県',
    region: 'CHUGOKU_SHIKOKU',
    website: 'https://www.okayama-skat.com/',
    twitter: 'Skat11111',
    instagram: 'skat11111',
    corich: 'https://stage.corich.jp/troupe/95623',
  },
  {
    name: '劇団ひびき',
    slug: 'gekidan-hibiki-okayama',
    groupType: 'AMATEUR',
    description: '岡山で60年以上の歴史を持つ老舗劇団。',
    foundedYear: 1962,
    prefecture: '岡山県',
    region: 'CHUGOKU_SHIKOKU',
  },
  {
    name: 'グンジョーブタイ',
    slug: 'gunjo-butai',
    groupType: 'AMATEUR',
    description: '「日常と非日常の曖昧さ」をコンセプトに広島を拠点に没入型演劇を開催。',
    foundedYear: 2013,
    prefecture: '広島県',
    region: 'CHUGOKU_SHIKOKU',
    website: 'https://www.gunjyobutai.com/',
  },
  {
    name: '劇団B-LUCKS',
    slug: 'gekidan-b-lucks',
    groupType: 'AMATEUR',
    description: '音楽・映像・芝居出身メンバーが集結し2008年に結成。広島を拠点に活動。',
    foundedYear: 2008,
    prefecture: '広島県',
    region: 'CHUGOKU_SHIKOKU',
    website: 'http://gekidan-b-lucks.com/',
  },
  {
    name: '劇団新波',
    slug: 'gekidan-shinpa',
    groupType: 'AMATEUR',
    description: '1981年結成。下関を拠点にオリジナル公演を行う演劇集団。',
    foundedYear: 1981,
    prefecture: '山口県',
    region: 'CHUGOKU_SHIKOKU',
    website: 'https://shinpa.com/',
  },
  {
    name: '劇団はぐるま座',
    slug: 'gekidan-hagurumaza',
    groupType: 'PROFESSIONAL',
    description: '1952年創設。下関市に本部を置き全国で公演活動を展開。原爆をテーマにした作品等で知られる。',
    foundedYear: 1952,
    prefecture: '山口県',
    region: 'CHUGOKU_SHIKOKU',
    website: 'https://haguruma-za.sakura.ne.jp/',
  },
  {
    name: '劇団回転木馬',
    slug: 'gekidan-kaiten-mokuba',
    groupType: 'AMATEUR',
    description: '2010年結成。高松市で活動し20代・30代の社会人が中心。',
    foundedYear: 2010,
    prefecture: '香川県',
    region: 'CHUGOKU_SHIKOKU',
  },
  {
    name: '劇団シアターホリック',
    slug: 'theater-holic-kochi',
    groupType: 'AMATEUR',
    description: '2004年旗揚げ。高知市を拠点に年2〜3回公演。',
    foundedYear: 2004,
    prefecture: '高知県',
    region: 'CHUGOKU_SHIKOKU',
    website: 'https://theaterholic.com/',
  },
  {
    name: 'TRY-ANGLE',
    slug: 'try-angle-kochi',
    groupType: 'AMATEUR',
    description: '1999年結成。高知市を拠点に年1〜2回公演。',
    foundedYear: 1999,
    prefecture: '高知県',
    region: 'CHUGOKU_SHIKOKU',
  },

  // ============================================================
  // 九州・沖縄 (KYUSHU_OKINAWA) - 28団体
  // ============================================================
  {
    name: '万能グローブ ガラパゴスダイナモス',
    slug: 'galapagos-dynamos',
    groupType: 'PROFESSIONAL',
    description: '2005年旗揚げ。ワンシチュエーションコメディを得意とする福岡の人気劇団。',
    foundedYear: 2005,
    prefecture: '福岡県',
    region: 'KYUSHU_OKINAWA',
    website: 'https://www.galapagos-dynamos.com/',
    instagram: 'galapa_d',
    corich: 'https://stage.corich.jp/troupe/281',
  },
  {
    name: "ギンギラ太陽's",
    slug: 'gingira-taiyous',
    groupType: 'PROFESSIONAL',
    description: '1997年発足。大塚ムネト主宰。福岡の街の建物を擬人化した「かぶりモノ」芝居で毎回3000人超の動員。',
    foundedYear: 1997,
    prefecture: '福岡県',
    region: 'KYUSHU_OKINAWA',
    website: 'https://gingira.com/',
  },
  {
    name: '飛ぶ劇場',
    slug: 'tobu-gekijou',
    groupType: 'PROFESSIONAL',
    description: '1987年に北九州市で結成。泊篤志主宰。第3回劇作家協会新人戯曲賞受賞。',
    foundedYear: 1987,
    prefecture: '福岡県',
    region: 'KYUSHU_OKINAWA',
    website: 'https://www.tobugeki.com/',
  },
  {
    name: '非・売れ線系ビーナス',
    slug: 'hi-uresenkei-venus',
    groupType: 'AMATEUR',
    description: '2003年結成。田坂哲郎主宰。福岡市を中心に活動。',
    foundedYear: 2003,
    prefecture: '福岡県',
    region: 'KYUSHU_OKINAWA',
    twitter: 'hi_uresen',
  },
  {
    name: '劇団HallBrothers',
    slug: 'gekidan-hall-brothers',
    groupType: 'AMATEUR',
    description: '1999年結成。幸田真洋が描く人間の暗部を滑稽に描く会話劇が特徴。第6回九州戯曲賞大賞受賞。',
    foundedYear: 1999,
    prefecture: '福岡県',
    region: 'KYUSHU_OKINAWA',
    website: 'https://www.h-bros.net/',
    twitter: 'gHallBros',
    instagram: 'ghallbros',
    corich: 'https://stage.corich.jp/troupe/399',
  },
  {
    name: '劇団ショーマンシップ',
    slug: 'gekidan-showmanship',
    groupType: 'PROFESSIONAL',
    description: '甘棠館Show劇場を拠点に時代劇からファミリーミュージカルまで幅広く上演。',
    prefecture: '福岡県',
    region: 'KYUSHU_OKINAWA',
    website: 'https://www.showman.jp/',
    twitter: 'showmanship_f',
    instagram: 'showmanship.official',
  },
  {
    name: '劇団風の子九州',
    slug: 'kazenoko-kyushu',
    groupType: 'PROFESSIONAL',
    description: '1985年に劇団風の子より独立。児童青少年向け演劇専門職業劇団。',
    foundedYear: 1985,
    prefecture: '福岡県',
    region: 'KYUSHU_OKINAWA',
    website: 'https://www.kazenoko-kyushu.com/',
    instagram: 'kazenoko_kyushu',
  },
  {
    name: '劇団ドリームカンパニー',
    slug: 'gekidan-dream-company',
    groupType: 'PROFESSIONAL',
    description: '1991年設立。「ビタミン・ミュージカル」をモットーにオリジナルミュージカルを全国で上演。',
    foundedYear: 1991,
    prefecture: '福岡県',
    region: 'KYUSHU_OKINAWA',
    website: 'https://www.dream-company.net/',
    corich: 'https://stage.corich.jp/troupe/1582',
  },
  {
    name: '劇団ティンカーベル',
    slug: 'gekidan-tinkerbell',
    groupType: 'AMATEUR',
    description: '福岡で34年以上活動するミュージカル劇団。',
    foundedYear: 1992,
    prefecture: '福岡県',
    region: 'KYUSHU_OKINAWA',
    twitter: 'tinkerbeII_m',
    instagram: 'gekidan_tinkerbell',
  },
  {
    name: '九州アクターズクラブ',
    slug: 'kyushu-actors-club',
    groupType: 'AMATEUR',
    description: '1999年発足。北九州と福岡を中心に活動するミュージカル劇団。',
    foundedYear: 1999,
    prefecture: '福岡県',
    region: 'KYUSHU_OKINAWA',
    website: 'http://katsclub1999.com/',
    twitter: 'katsclub1999',
  },
  {
    name: "F's Company",
    slug: 'fs-company-nagasaki',
    groupType: 'AMATEUR',
    description: '1997年結成の長崎の劇団。東京国際芸術祭参加実績あり。',
    foundedYear: 1997,
    prefecture: '長崎県',
    region: 'KYUSHU_OKINAWA',
    website: 'https://fs-company.com/',
  },
  {
    name: '劇団ヒロシ軍',
    slug: 'gekidan-hiroshi-gun',
    groupType: 'AMATEUR',
    description: '2007年に長崎県諫早市を拠点に旗揚げ。「青春・情熱・衝撃」がモットー。',
    foundedYear: 2007,
    prefecture: '長崎県',
    region: 'KYUSHU_OKINAWA',
    twitter: 'hiroshi_gun',
  },
  {
    name: '劇団きらら',
    slug: 'gekidan-kirara-kumamoto',
    groupType: 'PROFESSIONAL',
    description: '1985年結成。代表・池田美樹のオリジナル作品を上演。中高年の悩みをユーモラスに描く。',
    foundedYear: 1985,
    prefecture: '熊本県',
    region: 'KYUSHU_OKINAWA',
    website: 'http://www.gkirara.com/',
    twitter: 'gogomikitty',
    corich: 'https://stage.corich.jp/troupe/415',
  },
  {
    name: '096k熊本歌劇団',
    slug: '096k-kumamoto-kagekidan',
    groupType: 'PROFESSIONAL',
    description: '2020年旗揚げ。女性だけの歌劇団。殺陣・歌・ダンスに映像演出を融合。',
    foundedYear: 2020,
    prefecture: '熊本県',
    region: 'KYUSHU_OKINAWA',
    website: 'https://096k.jp/',
    twitter: '096k_official',
    instagram: '096k_official',
  },
  {
    name: '劇団石',
    slug: 'gekidan-ishi-kumamoto',
    groupType: 'AMATEUR',
    description: '熊本で51年以上の歴史。「まじめにあそぼう！」をモットーに活動。',
    foundedYear: 1973,
    prefecture: '熊本県',
    region: 'KYUSHU_OKINAWA',
    corich: 'https://stage.corich.jp/troupe/7641',
  },
  {
    name: '劇団立見席',
    slug: 'gekidan-tachimiseki',
    groupType: 'AMATEUR',
    description: '由布院を拠点に東京・大分で活動。演劇・映画・ドラマ・ラジオなど多方面で活躍。',
    prefecture: '大分県',
    region: 'KYUSHU_OKINAWA',
    website: 'https://www.tachimiseki.com/',
  },
  {
    name: '演劇集団P-nuts',
    slug: 'engeki-shudan-p-nuts',
    groupType: 'AMATEUR',
    description: '大分市を拠点に活動する演劇集団。',
    prefecture: '大分県',
    region: 'KYUSHU_OKINAWA',
    website: 'https://www.pnuts.biz/',
  },
  {
    name: '劇団こふく劇場',
    slug: 'cofuku-gekijou',
    groupType: 'PROFESSIONAL',
    description: '三股町立文化会館のフランチャイズカンパニー。こどもワークショップや市民参加型演劇フェスなど多角的に活動。',
    prefecture: '宮崎県',
    region: 'KYUSHU_OKINAWA',
    website: 'http://www.cofuku.com/',
  },
  {
    name: '劇団5-4',
    slug: 'gekidan-go-no-yon',
    groupType: 'AMATEUR',
    description: '沖縄県内各地のホールや小劇場で公演。FMラジオ番組も放送中。',
    prefecture: '沖縄県',
    region: 'KYUSHU_OKINAWA',
    website: 'https://gonoyon.com/',
    twitter: 'gkdn5n4',
  },
  {
    name: '劇団ビーチロック',
    slug: 'gekidan-beach-rock',
    groupType: 'PROFESSIONAL',
    description: '2014年設立。沖縄北部やんばるを拠点に亜熱帯の自然の中で演劇を創作。',
    foundedYear: 2014,
    prefecture: '沖縄県',
    region: 'KYUSHU_OKINAWA',
    website: 'https://www.beach69.net/',
  },
  {
    name: 'ACO沖縄',
    slug: 'aco-okinawa',
    groupType: 'PROFESSIONAL',
    description: '沖縄で30年以上続く舞台制作事務所。「劇場は命薬」をテーマに活動。',
    prefecture: '沖縄県',
    region: 'KYUSHU_OKINAWA',
    website: 'https://www.acookinawa.com/',
    twitter: 'aco_okinawa',
    instagram: 'aco_okinawa',
  },
];

// ========== メイン処理 ==========

async function main() {
  console.log('=== 小劇場劇団シード開始 ===\n');
  console.log(`投入対象: ${shogekijoGroups.length}団体\n`);

  let created = 0;
  let updated = 0;
  let errors = 0;

  for (const group of shogekijoGroups) {
    try {
      const existing = await prisma.theaterGroup.findUnique({ where: { slug: group.slug } });

      await prisma.theaterGroup.upsert({
        where: { slug: group.slug },
        update: {
          name: group.name,
          groupType: group.groupType,
          description: group.description ?? null,
          memberCount: group.memberCount ?? null,
          foundedYear: group.foundedYear ?? null,
          prefecture: group.prefecture,
          region: group.region,
          website: group.website ?? null,
          twitter: group.twitter ?? null,
          instagram: group.instagram ?? null,
          corich: group.corich ?? null,
          otherLinks: group.otherLinks ?? [],
        },
        create: {
          name: group.name,
          slug: group.slug,
          groupType: group.groupType,
          description: group.description ?? null,
          memberCount: group.memberCount ?? null,
          foundedYear: group.foundedYear ?? null,
          prefecture: group.prefecture,
          region: group.region,
          website: group.website ?? null,
          twitter: group.twitter ?? null,
          instagram: group.instagram ?? null,
          corich: group.corich ?? null,
          otherLinks: group.otherLinks ?? [],
        },
      });

      if (existing) {
        updated++;
      } else {
        created++;
      }
    } catch (e) {
      errors++;
      console.error(`  エラー: ${group.name} (${group.slug}) - ${e}`);
    }
  }

  console.log(`\n=== 処理完了 ===`);
  console.log(`  新規作成: ${created}団体`);
  console.log(`  更新: ${updated}団体`);
  if (errors > 0) console.log(`  エラー: ${errors}件`);

  // 結果サマリ
  const totalCount = await prisma.theaterGroup.count();
  const byType = await prisma.theaterGroup.groupBy({
    by: ['groupType'],
    _count: { id: true },
  });
  const byRegion = await prisma.theaterGroup.groupBy({
    by: ['region'],
    _count: { id: true },
  });

  console.log(`\n=== DB全体のサマリ ===`);
  console.log(`  劇団総数: ${totalCount}団体`);
  console.log(`  タイプ別:`);
  for (const t of byType) {
    console.log(`    ${t.groupType}: ${t._count.id}団体`);
  }
  console.log(`  地域別:`);
  for (const r of byRegion) {
    console.log(`    ${r.region ?? '未設定'}: ${r._count.id}団体`);
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
